name: Build

on:
  push:
    branches: [ main, local-dev ]
  pull_request:
    branches: [ main, local-dev ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        lfs: 'true'

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        check-latest: true
        go-version-file: 'go.mod'

    - name: Build
      run: make build

    - name: Test
      run: make test

    - name: Install dependencies
      run: |
        go install github.com/mickael-menu/tesh@latest

    - name: Tesh
      # See https://github.com/actions/runner/issues/241#issuecomment-924327172
      shell: script --return --quiet --command "bash {0}"
      run: make tesh

